spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:policytracker_test}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:test}:${MONGO_PASSWORD:test}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:policytracker_test}?authSource=admin

external-insurance:
  base-url: ${EXTERNAL_INSURANCE_BASE_URL:http://localhost:18080/mock-external-insurance}

reference-data-import:
  csv:
    default-source-path: ${REFERENCE_DATA_IMPORT_CSV_PATH:./src/test/resources/reference-data-test.csv}

system-properties:
  defaults:
    externalinsurance-events-enabled: true
